% create pitch period contour -- create_pitch_period_contour.m
%
    clear all;
    
% create linear contour starting at PP_Begin at frame 1 and ending at
% PP_End at frame nfrm
    PP_Begin=160;
    PP_End=40;
    nfrm=100;
    fs=10000;
    R=10*fs/1000;
    
% create array of pitch periods
    PP(1:nfrm)=round(PP_Begin+(PP_End-PP_Begin).*(0:nfrm-1)/(nfrm-1));
    figure;plot(1:nfrm,PP,'r','LineWidth',2);xlabel('frame number');
    ylabel('pitch period (samples)'),grid on;axis tight;

% create pitch pulse contour
    e=zeros(nfrm*R,1);
    e(1)=1;
    esav=1;
    Rind=R;
    for i=1:nfrm;
        while (esav+PP(i) < Rind)
            e(esav+PP(i))=1;
            esav=esav+PP(i);
        end
        Rind=Rind+R;
    end
        
% plot pitch excitation
    figure;plot(0:length(e)-1,e,'r','LineWidth',2);
    xlabel('time in samples');ylabel('value');grid on;axis tight;
  
    alpha1=0.25;
    alpha2=0.10;
    period=10*fs/1000;
% form rosenberg pulse
    n1=round(period*alpha1);
    n2=round(period*alpha2);
    g=[];
    x1=0:n1;
    g=[g 0.5*(1-cos(pi*x1/n1))];
    x2=1:n2;
    g=[g cos(pi*x2/(2*n2))];
    g=[g zeros(1,period-length(g))];
    
% plot glottal pulse
    figure;plot(0:period-1,g,'r','LineWidth',2);xlabel('time in samples');
    ylabel('value');grid on;axis tight;
    
% Inputs:
%   ivowel: index of one of 10 vowels
%   fs: signal processing sampling rate
%   nfft: fft size
%   pd: pitch period in samples
%   nsamp: number of samples in vowel sound

% read in vowel formants and bandwidth choices for set of 10 vowels
% mat file vowels_fmts_bw.mat loads list of vowel names, vowels(10,2),
% formants (10,3), and bandwidths (1,4)
    str=load('vowels_fmts_bw.mat');
    bandwidths=str.bandwidths;
    formants=str.formants;
    vowels=str.vowels;
    
% generate selected vowel impulse response using 3 formants (fourth fixed
% at 4000 Hz), and 4 bandwidths; impulse response generated by using an
% impulse at the input of the first of 4 second-order systems, with the
% output of each system being used to excite the next second-order system
    nfft=2048;
    ivowel=10;
    xin=[1 zeros(1,nfft/2-1)];
    for resonance=1:4
        if (resonance < 4)
            f=formants(ivowel,resonance);
        else
            f=4000;
        end
        bw=bandwidths(1,resonance);
        num=1-2*exp(-bw*2*pi/fs)*cos(2*pi*f/fs)+exp(-2*bw*2*pi/fs);
        den=[1 -2*exp(-bw*2*pi/fs)*cos(2*pi*f/fs) exp(-2*bw*2*pi/fs)];
        yout=filter(num,den,xin);
        xin=yout;
    end
    
% plot vowel response
    figure;subplot(211),plot(0:199,xin(1:200),'k');xlabel('time in samples');
    ylabel('value');grid on;axis tight;
    YOUT=fft(yout,nfft);
    YOUTL=20*log10(abs(YOUT));
    subplot(212),plot(0:fs/nfft:fs/2,YOUTL(1:nfft/2+1),'r','LineWidth',2);
    xlabel('frequency');ylabel('log magnitude (dB)');grid on; axis tight;
    
% convolve vowel response with glottal pulse and then with pitch excitation
    y1=conv(xin,g);
    y2=conv(y1,e);
    
% plot convolved sequence
    figure;plot(0:499,y2(1:500),'r','LineWidth',2);xlabel('time in samples');
    ylabel('value');grid on;axis tight;
    
% play out convolved sequence
    soundsc(y2,fs);
    
% plot linear and log magnitude spectrums
    clear Y2 Y2A  Y2L;
    Y2=fft(y2(1:500),nfft);
    Y2A=abs(Y2);
    Y2L=20*log10(Y2A);
    figure;subplot(211),plot(0:fs/nfft:fs/2,Y2A(1:nfft/2+1),'r');grid on;
    axis tight;
    subplot(212),plot(0:fs/nfft:fs/2,Y2L(1:nfft/2+1),'b');
    xlabel('frequency'),ylabel('linear/log magnitude');grid on; axis tight;