%%Megan attempts to synthesize formants based on input from touchscreen location
%Based on code from Vowel_Synthesis_GUI25.m (source code on Matlab Central)
%http://www.mathworks.com/matlabcentral/fileexchange/45449-vowel-synthesis
%Credit Rabiner, Shafer
function formant_synthesize_silence(f1,f2)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Dummy file for initializing the program without making a sound to handle
%the slow start to the hook setup
% Initialize Variables
    %fs=10000;
    %fsr=10000;
    nfft=2048; %Seems to have something to do with sampling, sounds fine when half size, really nasaly/robotic when very small
    %pd=100.5;
    ivowel=1;
    %nsamp=2000;
    R=60;%Determines how long playback is, seemingly the time in centiseconds (100=1second)
    %Rm=10;
    %Just leave the pitch hard-coded. Eventually shift via subject
    %Future experiment idea: See if people learn better if pitch
    %subject-matched
    PF_Beg=60;
    PP_Beg=60;
    PF_End=60;
    PP_End=60;
    nfrm=60;
    y2=[];

% fs: signal sampling rate
    %For now, sampling rate hard-coded. Will investigate latter what
    %exactly it does.
    fs = 6000; 
        
% create array of pitch periods
    PP(1:nfrm)=round(PP_Beg+(PP_End-PP_Beg).*(0:nfrm-1)/(nfrm-1));    
    
% create pitch pulse contour
    e=zeros(nfrm*R,1);
    e(1)=1;
    esav=1;
    Rind=R;
    for i=1:nfrm;
        while (esav+PP(i) < Rind)
            e(esav+PP(i))=1;
            esav=esav+PP(i);
        end
        Rind=Rind+R;
    end
        
%I honestly have no idea what these do but it doesn't seem to run without
%them
% create glottal pulse
    alpha1=0.25;
    alpha2=0.10;
    period=10*fs/1000;
    
% form rosenberg pulse
    n1=round(period*alpha1);
    n2=round(period*alpha2);
    g=[];
    x1=0:n1;
    g=[g 0.5*(1-cos(pi*x1/n1))];
    x2=1:n2;
    g=[g cos(pi*x2/(2*n2))];
    g=[g zeros(1,period-length(g))];

% read in vowel formants and bandwidth choices for set of 10 vowels
% mat file vowels_fmts_bw.mat loads list of vowel names, vowels(10,2),
% formants (10,3), and bandwidths (1,4)

%This will eventually be re-worked to be based on mouse location
    str=load('vowels_fmts_bw.mat');
    bandwidths=str.bandwidths;
    %formants=str.formants;
    f1 = double(f1);
    f2 = double(f2);
    formants = [f1 f2 2500];
    %vowels=str.vowels;

% generate selected vowel impulse response using 3 formants (fourth fixed
% at 4000 Hz), and 4 bandwidths; impulse response generated by using an
% impulse at the input of the first of 4 second-order systems, with the
% output of each system being used to excite the next second-order system
    xin=[1 zeros(1,nfft/2-1)];
    for resonance=1:4
        if (resonance < 4)
            f=formants(ivowel,resonance);
        else
            f=4000;
        end
        bw=bandwidths(1,resonance);
        num=1-2*exp(-bw*2*pi/fs)*cos(2*pi*f/fs)+exp(-2*bw*2*pi/fs);
        den=[1 -2*exp(-bw*2*pi/fs)*cos(2*pi*f/fs) exp(-2*bw*2*pi/fs)];
        yout=filter(num,den,xin);
        xin=yout;
    end
    
    % convolve vowel response with glottal pulse and then with pitch excitation
    y1=conv(xin,g);
    y2=conv(y1,e);
    
    
    % play out convolved sequence
    %soundsc(y2,fs);